# Generated by Django 5.2.13 on 2026-04-18 20:45

import users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=users.models.user.get_user_directory_path),
        ),
    ]
