# Generated by Django 5.2.13 on 2026-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_status_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_emoji',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
