services:
  web:
    build:
      target: production
    restart: always

  client:
    build:
      target: production
    restart: always
    ports:
      - "80:80"

  db:
    restart: always

  redis:
    restart: always
