name: Lint Client Skip

on:
  pull_request:
    # Trigger this ONLY when the client files are NOT touched
    paths-ignore:
      - "client/**"
      - ".github/workflows/**"

jobs:
  lint:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Skip Client Linting
        run: echo "No client changes detected. Skipping linting to save CI minutes!"
